name: Bug report for bnb
description: Issue report for bnb website
title: "[Bug Report]: "
labels: [bug, needs-triage]
body:
  - type: textarea
    id: what-happened-expect
    attributes:
      label: What did you expect to happen?
      description: Include the steps you took and define what you expected from these steps.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: what-happened-actual
    attributes:
      label: What actually happened?
      description: Include the steps you took and outline why or how this did not meet expectations.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: bnb version
      description: What version of bnb are you running?
      placeholder: v1.27.4
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform & operating system
      description: On what platform(s) are you seeing the problem? Please include the bit version.
      placeholder: Windows 10 64 Bit
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser version
      description: If the problem is related to the GUI, describe your browser and version.
      placeholder: Chrome 123.0.6312.86
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: What hardware were you using when you encountered the issue?
      description: Please specify your hardware setup.
      placeholder: What were you using?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output and error messages
      description: Please copy and paste any relevant log output or error messages. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

