blank_issues_enabled: false
contact_links:
  - name: Contact Us
    url: https://example.com/contact
    about: Please contact us if your issue is not listed here.
issue_templates:
  - name: Bug report for bnb
    description: Create a report to help us improve
    template: bug_report.yml
    title: "[Bug Report]"
    labels: [bug, needs-triage]

